cd C:\Windows\
@echo off
cls

AMIDEWINx64.EXE /IVN %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /IV %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /IV %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /SM %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /SP %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /SV %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /SS %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /SU AUTO >nul
AMIDEWINx64.EXE /SK %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /SF %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /BM %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /BP %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /BV %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /BS %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /BT %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /BLC %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /CM %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /CV %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /CS %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /CA %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /CSK %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /PSN %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /PAT %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /PPN %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 1 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 2 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 3 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 4 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 5 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 6 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 7 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 8 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 9 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 10 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul
AMIDEWINx64.EXE /OS 11 %RANDOM%-%RANDOM%-%RANDOM%-%RANDOM% >nul



